[build]
  command = "npm run build"
  publish = "out"

[dev]
  command = "next dev"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200